### ISSUE TITLE
About allocations in vector addition and other operations

### ISSUE THREAD

**Issue by ivanquirino** [thejustinwalsh/defold-xmath#6]
On this snippet of code from the library:

```c++
 Vectormath::Aos::Vector3 *out = dmScript::CheckVector3(L, 1);
 Vectormath::Aos::Vector3 *lhs = dmScript::CheckVector3(L, 2);
 Vectormath::Aos::Vector3 *rhs = dmScript::CheckVector3(L, 3);
 *out = *lhs + *rhs;
```
The `*lhs + *rhs` operation does indeed allocate a new vector3, right? And then assign the new vector to the out vector, which would be one of the other two arguments. For me, this is just creating a new vector like defold does and assigning it to an existing reference, instead of doing the operation in place. Or am I missing something?

To really do the operation in place, it would have to add individual components to the out vector, something like (my C/C++ skills are rusted):
```
*out->x = *lhs->x + *rhs->x
*out->y = *lhs->y + *rhs->y
*out->z = *lhs->z + *rhs->z
```

This I suppose, would actually add in-place, changing the `out` vector. Please correct me if I'm wrong.

**Comment by thejustinwalsh** [comment]
Vectors in Defold are Lua UserData, which means that every time you make a new vector in Lua, you allocate memory for the user data and then push that onto the Lua stack.

My extension allows you to reuse existing user data repeatedly for the same `out` result.

If you look at the implementation of `Vector3_add` you will see that it uses the method `PushVector3`
https://github.com/defold/defold/blob/67565e3bde1b533b96640a24c63e2d755efb055e/engine/script/src/script_vmath.cpp#L265

This requires that a new Vector3 is allocated with the [lua_newuserdata](https://www.lua.org/pil/28.1.html) with every call to add, or any other of the math operations.

On the C++ side, we are getting pointers to the left, right, and out values, then using the overloaded `+` operator to add them and move the result into the out value. We are not allocating off the heap, and the temporary that resulted from the add will be compiled down to setting the values from the registers.

Additionally, the overloaded operator has the potential of using SIMD/vectorized operations on hardware that supports it, making the overloaded + operator faster than the long form assignment component by component because the CPU can add all three at the same time in one instruction.

The example on the README is the intended use, where I allocate one temporary vector v, and reuse it through the lifetime of the program, everywhere that I call an xmath function using v as the output, I save the allocation that PushVector3 creates when you use the add method directly in lua.

**Comment by ivanquirino** [comment]
That was helpful! Thank you for the explanation!
